### ISSUE TITLE
Handle reserved Windows filenames

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/filenamify#1]
By using https://github.com/sindresorhus/filename-reserved-regex#filenamereservedregexwindowsnames and if it matches, add the replacement character to the end of the filename.

@silverwind What do you think?

**Comment by silverwind** [comment]
Sounds good.

**Comment by daveseco7** [comment]
As it stands, this issue relies on `filenameReservedRegex.windowsNames()`. Currently, such regex is only available on version 2.0.0 of the _filename-reserved-regex_. Executing `npm install filenamify --save` will pull by default version 1.0.0 of _filename-reserved-regex_. Adding this feature to **filenamify** will force the update of the dependency mentioned above. 
Whenever I get a little free time I will try to implement such feature, as well as a  couple of unit tests.
