### ISSUE TITLE
Replacement option removes processed string last character

### ISSUE THREAD

**Issue by dmnsgn** [sindresorhus/filenamify#11]
```js
import filenamify from "filenamify";

console.log(filenamify('my <file name-', { replacement: '-' }))
console.log(filenamify('my <file name<', { replacement: '-' }))
console.log(filenamify('my <file name<'))

// > console output
my -file name   // Expected: my -file name-
my -file name   // Expected: my -file name-
my !file name   // Expected: my !file name!
```

See above example,  the invalid `<` character is replaced the first time BUT the last character `-` or `<` is deleted if it is:
- the same character as the replacement option
- the same character after replacing it if invalid
- an invalid character

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the previous attempt and feedback in https://github.com/sindresorhus/filenamify/pull/12.
