### ISSUE TITLE
Doesn't rename files containing a pipe character

### ISSUE THREAD

**Issue by svandragt** [sindresorhus/filenamify#20]
I have this filename `2021-03-19 Track and Trace - Track your Item | Royal Mail Ltd.pdf` which is a PDF saved from Safari, where webpages often include a pipe character to delineate the page title from the site title.

The pipe character is not a valid filename character on Windows 10, but filenamify didn't rename it.

**Comment by papb** [comment]
Unable to reproduce:

```js
const filenamify = require('filenamify');

filenamify('2021-03-19 Track and Trace - Track your Item | Royal Mail Ltd.pdf');
//=> "2021-03-19 Track and Trace - Track your Item ! Royal Mail Ltd.pdf"
```

[Try it on RunKit](https://npm.runkit.com/filenamify)

**Comment by svandragt** [comment]
yeah ok it's not the pipe character. weird.

```
$ filenamify 2021-03-19\ Track\ and\ Trace\ -\ Track\ your\ Item\ \|\ Royal\ Mail\ Ltd.pdf
2021-03-19 Track and Trace - Track your Item ! Royal Mail Ltd.pdf
$ ls
'2021-03-19 Track and Trace - Track your Item | Royal Mail Ltd.pdf'
$ cp 2021-03-19\ Track\ and\ Trace\ -\ Track\ your\ Item\ \|\ Royal\ Mail\ Ltd.pdf "royal | mail.pdf"
$ filenamify royal\ \|\ mail.pdf
royal ! mail.pdf
$ ls
'2021-03-19 Track and Trace - Track your Item | Royal Mail Ltd.pdf'
'royal | mail.pdf'
```

**Comment by svandragt** [comment]
Nevermind, my bad. It doesn't promise to actually rename the file. 😬
