### ISSUE TITLE
File name with ! (Exclamation mark only) return blank

### ISSUE THREAD

**Issue by patil-milind** [sindresorhus/filenamify#21]
**Version:** 4.2.0
**Actual:**   If any file contains only the !!!!!.docx name then the filenamify return .docx only the extension file name gets blank.
**Expected:**  As exclamation (!) mark is the valid filename character this should return the same name.

**Comment by sindresorhus** [comment]
This is indeed a bug. It's because `!` is out replacement character.

**Comment by noncash15** [comment]
#21

**Comment by noncash15** [comment]
Fix issue #21
