### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by astoilkov** [sindresorhus/filenamify#28]
Have you considered running `path.normalize('NFD')` to the filename?

Why?
- See https://www.reddit.com/r/MacOS/comments/jhjv41/psa_beware_of_umlauts_and_other_accented/
- On macOS the file system normalizes the path and `actualFileName !== filenamify(fileName)`
- When creating files inside of Dropbox the problem is even bigger because Node.JS returns the actual file name but you should wait before trying to retrieve the name (some milliseconds that may differ on each system).

**Comment by sindresorhus** [comment]
Good idea 👍
