### ISSUE TITLE
Pre-compile to es5?

### ISSUE THREAD

**Issue by cheapsteak** [sindresorhus/filenamify#3]
Getting this error when using filenamify in a create-react-app app

```bash
Failed to minify the code from this file:

 	./node_modules/filenamify/index.js:13

Read more here: [http://bit.ly/2tRViJ9](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)
```

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
