### ISSUE TITLE
NestJs ES Module not supported

### ISSUE THREAD

**Issue by tyzion** [sindresorhus/filenamify#41]
Hi all,

Thanks for this package!

I'm encountering this problem, see the screenshot, with my nestjs app (cli version 10.3.2). I'm using a docker container to run my app. 
I saw that there's already a closed issue about this, but seems like I can't use this package, no matter how I try to import it.
Can you help me?

Thanks in advance! 

![Screenshot from 2024-08-26 09-30-48](https://github.com/user-attachments/assets/0f445667-a771-4b6c-a0e3-d63509655c34)

**Comment by sindresorhus** [comment]
This is a problem with Nest.js. You should open an issue on their issue tracker instead.

**Comment by tyzion** [comment]
oh ok, sorry,
I'll try there, thanks!
