### ISSUE TITLE
Make max filename size configurable

### ISSUE THREAD

**Issue by CaffeinatedCM** [sindresorhus/filenamify#5]
My use case requires longer filenames, but currently, that isn't configurable.

**Comment by sindresorhus** [comment]
What's the use-case? 100 is already a lot.

**Comment by WolfieZero** [comment]
I think most OS are limited to 255 characters? 

While I do agree anything more than 100 is a lot, I think the limit of 100 is some-what opinionated. It would be good to set a hard limit of 255 (assuming I'm correct) and a configurable default of 100. Best of both worlds then.
